package sys.model;
// Generated 23/05/2018 21:26:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbcidade generated by hbm2java
 */
public class Tbcidade  implements java.io.Serializable {


     private Integer idcidade;
     private Tbestado tbestado;
     private String nomecidade;
     private Set<Tbempregado> tbempregados = new HashSet<Tbempregado>(0);

    public Tbcidade() {
    }

    /**
     * 
     * @param tbestado
     * @param nomecidade 
     */
    public Tbcidade(Tbestado tbestado, String nomecidade) {
        this.tbestado = tbestado;
        this.nomecidade = nomecidade;
    }
    /**
     * 
     * @param tbestado
     * @param nomecidade
     * @param tbempregados 
     */
    public Tbcidade(Tbestado tbestado, String nomecidade, Set<Tbempregado> tbempregados) {
       this.tbestado = tbestado;
       this.nomecidade = nomecidade;
       this.tbempregados = tbempregados;
    }
    /**
     * 
     * @return 
     */
    public Integer getIdcidade() {
        return this.idcidade;
    }
    
    public void setIdcidade(Integer idcidade) {
        this.idcidade = idcidade;
    }
    public Tbestado getTbestado() {
        return this.tbestado;
    }
    
    public void setTbestado(Tbestado tbestado) {
        this.tbestado = tbestado;
    }
    public String getNomecidade() {
        return this.nomecidade;
    }
    
    public void setNomecidade(String nomecidade) {
        this.nomecidade = nomecidade;
    }
    public Set<Tbempregado> getTbempregados() {
        return this.tbempregados;
    }
    
    public void setTbempregados(Set<Tbempregado> tbempregados) {
        this.tbempregados = tbempregados;
    }




}


