package sys.model;
// Generated 23/05/2018 21:26:43 by Hibernate Tools 4.3.1



/**
 * Tbempregado generated by hbm2java
 */
public class Tbempregado  implements java.io.Serializable {


     private Integer idempregado;
     private Tbcidade tbcidade;
     private Tbestado tbestado;
     private Tbpais tbpais;
     private String nome;
     private String sobrenome;
     private String endereco;
     private String codigoArea;
     private String telefone;

    public Tbempregado() {
    }

    public Tbempregado(Tbcidade tbcidade, Tbestado tbestado, Tbpais tbpais, String nome, String sobrenome, String endereco, String codigoArea, String telefone) {
       this.tbcidade = tbcidade;
       this.tbestado = tbestado;
       this.tbpais = tbpais;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.endereco = endereco;
       this.codigoArea = codigoArea;
       this.telefone = telefone;
    }
   
    public Integer getIdempregado() {
        return this.idempregado;
    }
    
    public void setIdempregado(Integer idempregado) {
        this.idempregado = idempregado;
    }
    public Tbcidade getTbcidade() {
        return this.tbcidade;
    }
    
    public void setTbcidade(Tbcidade tbcidade) {
        this.tbcidade = tbcidade;
    }
    public Tbestado getTbestado() {
        return this.tbestado;
    }
    
    public void setTbestado(Tbestado tbestado) {
        this.tbestado = tbestado;
    }
    public Tbpais getTbpais() {
        return this.tbpais;
    }
    
    public void setTbpais(Tbpais tbpais) {
        this.tbpais = tbpais;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }




}


