package sys.model;
// Generated 23/05/2018 21:26:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbpais generated by hbm2java
 */
public class Tbpais  implements java.io.Serializable {


     private Integer idpais;
     private String nomepais;
     private Set<Tbempregado> tbempregados = new HashSet<Tbempregado>(0);
     private Set<Tbestado> tbestados = new HashSet<Tbestado>(0);

    public Tbpais() {
    }

	
    public Tbpais(String nomepais) {
        this.nomepais = nomepais;
    }
    public Tbpais(String nomepais, Set<Tbempregado> tbempregados, Set<Tbestado> tbestados) {
       this.nomepais = nomepais;
       this.tbempregados = tbempregados;
       this.tbestados = tbestados;
    }
   
    public Integer getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(Integer idpais) {
        this.idpais = idpais;
    }
    public String getNomepais() {
        return this.nomepais;
    }
    
    public void setNomepais(String nomepais) {
        this.nomepais = nomepais;
    }
    public Set<Tbempregado> getTbempregados() {
        return this.tbempregados;
    }
    
    public void setTbempregados(Set<Tbempregado> tbempregados) {
        this.tbempregados = tbempregados;
    }
    public Set<Tbestado> getTbestados() {
        return this.tbestados;
    }
    
    public void setTbestados(Set<Tbestado> tbestados) {
        this.tbestados = tbestados;
    }




}


